#!/bin/sh
echo HELLO!!!
echo HELLO!!!
echo HELLO!!!
echo
echo "starting dbus"
/usr/bin/dbus-daemon --system --nofork --nopidfile --syslog-only
echo "starting iwd"
/usr/bin/iwd/iwd
echo "entering tty"
/sbin/agetty 9600 tty1
